# SPDX-License-Identifier: MIT-0
---
# tasks file for postgres
- name: Install the latest versions of postgresql
  ansible.builtin.package:
    name:
      - postgresql
      - postgresql-server
    state: present
