# SPDX-License-Identifier: MIT-0
---
# tasks file for postgres
- name: "Install the latest versions of postgresql"
  when: ansible_facts['os_family'] not in ['Darwin']
  ansible.builtin.include_tasks: "{{ _install_tasks_file }}"
  with_first_found:
    - "install-{{ ansible_facts['os_family'] }}.yaml"
  loop_control:
    loop_var: _install_tasks_file
