#SPDX-License-Identifier: MIT-0
---
# vars file for etcd

etcd_ver: v3.6.5
etcd_package_repo: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_ver }}/etcd-{{ etcd_ver }}-linux-amd64.tar.gz"
