#SPDX-License-Identifier: MIT-0
---
# defaults file for patroni
# vars file for patroni

archived_dir: /home/postgres/archived

# Debian
postgres_config_dir: /etc/postgresql/17/main
postgres_data_dir: /var/lib/postgresql/17/main
postgres_bin_dir: /usr/lib/postgresql/17/bin

# RedHat
#postgres_config_dir: /var/lib/pgsql/data
#postgres_data_dir: /var/lib/pgsql/data
#postgres_bin_dir: /usr/bin