#SPDX-License-Identifier: MIT-0
---
# handlers file for patroni

- name: Restart patroni
  ansible.builtin.service:
    name: patroni
    state: restarted
    enabled: true
  when: is_master is defined and is_master == 'false'